apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: immich-ml-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: immich-ml
  policy:
    semver:
      range: ">=1.0.0"
