apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: radicale-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: radicale
  policy:
    alphabetical:
      order: asc
  filterTags:
    # Limits the first digit to 1 or 2 characters to ignore '386' prefixes
    # Matches: 3.6.0.0, 10.1.2.3
    # Ignores: 386.3.0.6.3
    pattern: '^([0-9]{1,2}(?:\.[0-9]+)+)$'
    extract: '$1'

