apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: radicale-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: radicale
  policy:
    semver:
      range: ">=1.0.0"
  filterSelection:
    # Captures the first 3 numeric segments to satisfy SemVer rules
    # but still allows the full tag to be used if matched.
    extract: '$1.$2.$3'
    regex: '^([0-9]+)\.([0-9]+)\.([0-9]+)(?:\.[0-9]+)?$'

