apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageUpdateAutomation
metadata:
  name: image-update-automation
  namespace: flux-system
spec:
  interval: 1h
  sourceRef:
    kind: GitRepository
    name: kubernetes-repo
  git:
    checkout:
      ref:
        branch: main
    commit:
      author: # Fixed field name from 'authorName' to 'author'
        email: flux@casa.local
        name: Flux Bot
      messageTemplate: |
        chore: update images
        {{range .Updated.Images -}}
        - {{.NewImage}}
        {{end}}
    push:
      branch: main # Or the branch you want to push directly to
  update:
    strategy: Setters
    path: ./ 

