{{- $existingGateway := (lookup "gateway.networking.k8s.io/v1" "Gateway" .Values.gateway.namespace .Values.gateway.name) -}}
{{- if not $existingGateway -}}
# Gateway resource that defines the listeners for Syncthing.
# It is automatically created if it doesn't already exist in the cluster.
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ .Values.gateway.name }}
  namespace: {{ .Values.gateway.namespace }}
spec:
  gatewayClassName: {{ .Values.gateway.gatewayClassName | default "traefik" }}
  listeners:
    - name: websecure
      port: 8443
      protocol: HTTPS
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate
        {{- if .Values.gateway.certificateName }}
        certificateRefs:
          - name: {{ .Values.gateway.certificateName }}
        {{- end }}
    - name: syncthing-tcp
      port: {{ .Values.service.syncTcpPort }}
      protocol: TCP
      allowedRoutes:
        kinds:
          - group: gateway.networking.k8s.io
            kind: TCPRoute
        namespaces:
          from: All
    - name: syncthing-udp
      port: {{ .Values.service.syncUdpPort }}
      protocol: UDP
      allowedRoutes:
        kinds:
          - group: gateway.networking.k8s.io
            kind: UDPRoute
        namespaces:
          from: All
{{- end -}}
