apiVersion: v2
name: weather-station-postgres
description: A Helm chart wrapper for PostgreSQL using Bitnami PostgreSQL chart
type: application
version: 0.1.0
appVersion: "18.3.0"

dependencies:
  - name: postgresql
    repository: oci://registry-1.docker.io/bitnamicharts
    version: 18.5.1
    condition: postgresql.enabled