apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: kubernetes-repo
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/adonis28850/kubernetes
  # The 'branch' field must be inside 'ref'
  ref:
    branch: main
  # Also, link your secret here if you want to use it for authentication
  secretRef:
    name: github-token

